-- Production plans table schema
-- Based on app/models/production_plan.py ProductionPlan model

-- Production plans table
CREATE TABLE IF NOT EXISTS production_plans (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    educational_objective TEXT NOT NULL,
    scene_count INT NOT NULL,
    narration_style VARCHAR(100),
    visual_style VARCHAR(100),
    character_requirements JSONB,
    music_mood_plan TEXT,
    animation_style_plan TEXT,
    thumbnail_concept_plan TEXT,
    seo_strategy_plan JSONB,
    quality_rules JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_production_plans_project_id ON production_plans(project_id);
CREATE INDEX IF NOT EXISTS idx_production_plans_created_at ON production_plans(created_at);

-- Comments
COMMENT ON TABLE production_plans IS 'Table storing production plans generated by the Director Agent';
COMMENT ON COLUMN production_plans.id IS 'Unique identifier for the production plan';
COMMENT ON COLUMN production_plans.project_id IS 'Reference to the project this plan belongs to';
COMMENT ON COLUMN production_plans.educational_objective IS 'Educational objective of the video';
COMMENT ON COLUMN production_plans.scene_count IS 'Number of scenes in the production plan';
COMMENT ON COLUMN production_plans.narration_style IS 'Narration style for the video';
COMMENT ON COLUMN production_plans.visual_style IS 'Visual style for the video';
COMMENT ON COLUMN production_plans.character_requirements IS 'JSONB structure detailing character requirements';
COMMENT ON COLUMN production_plans.music_mood_plan IS 'Plan for music mood and style';
COMMENT ON COLUMN production_plans.animation_style_plan IS 'Plan for animation style and techniques';
COMMENT ON COLUMN production_plans.thumbnail_concept_plan IS 'Concept plan for thumbnails';
COMMENT ON COLUMN production_plans.seo_strategy_plan IS 'JSONB structure containing SEO strategy';
COMMENT ON COLUMN production_plans.quality_rules IS 'JSONB structure containing quality rules and thresholds';
COMMENT ON COLUMN production_plans.created_at IS 'Timestamp when production plan was created';