-- Story scripts table schema
-- Based on app/models/story_script.py StoryScript model

-- Story scripts table
CREATE TABLE IF NOT EXISTS story_scripts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    story_title VARCHAR(255) NOT NULL,
    story_summary TEXT NOT NULL,
    educational_goal TEXT NOT NULL,
    ending_call_to_action TEXT,
    characters JSONB NOT NULL,
    scenes JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_story_scripts_project_id ON story_scripts(project_id);
CREATE INDEX IF NOT EXISTS idx_story_scripts_created_at ON story_scripts(created_at);

-- Comments
COMMENT ON TABLE story_scripts IS 'Table storing story scripts generated by the Story Agent';
COMMENT ON COLUMN story_scripts.id IS 'Unique identifier for the story script';
COMMENT ON COLUMN story_scripts.project_id IS 'Reference to the project this script belongs to';
COMMENT ON COLUMN story_scripts.story_title IS 'Title of the story';
COMMENT ON COLUMN story_scripts.story_summary IS 'Summary of the story';
COMMENT ON COLUMN story_scripts.educational_goal IS 'Educational goal of the story';
COMMENT ON COLUMN story_scripts.ending_call_to_action IS 'Call to action at the end of the story';
COMMENT ON COLUMN story_scripts.characters IS 'JSONB structure containing character information';
COMMENT ON COLUMN story_scripts.scenes IS 'JSONB structure containing scene-by-scene breakdown';
COMMENT ON COLUMN story_scripts.created_at IS 'Timestamp when story script was created';